### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by markusschaber** [AsherBarak/LINQ-Expression-Projection#2]
There's no license / copying file, nor any license statement in the source files.

To enble others to use your code in a legally safe way, you should add an official license.

If all code here is yours (no code copied from somewhere else), and you don't care, I sugest the MIT license which is simple, and also used by .NET Core.

**Comment by AsherBarak** [comment]
Thanks,

MIT it is. 

Enjoy

**Comment by markusschaber** [comment]
Thank you very much! :-)
